import type { Metadata } from "next";
import { Belleza, Inter } from "next/font/google";
import TopNav from "./_components/topnav";
import "./globals.css";
import Loading from "./loading";
import { Playfair_Display, Great_Vibes } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-playfair",
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-greatvibes",
});

const belleza = Belleza({
    variable: "--font-belleza",
    weight: "400",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Beauty by Chloe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en"
            className={`${inter.variable} ${belleza.variable} ${playfair.variable} ${greatVibes.variable}`}>
            <body>
            {children}
        </body>
        </html >
    );
}
