import type { Metadata } from "next";
import { Belleza, Inter } from "next/font/google";
import TopNav from "./_components/topnav";
import "./globals.css";

const belleza = Belleza({
  variable: "--font-belleza",
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Beauty by Chloe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en"
        className={`${inter.variable} ${belleza.variable}`}>
            <body>
                {children}
            </body>
        </html>
    );
}
